<div style="
background: linear-gradient(135deg, #f3e8ff, #ddd6fe);
padding:20px;
border-radius:15px;
text-align:center;
box-shadow:0 3px 8px rgba(0,0,0,0.1);
margin:auto;
">

<h2 style="
margin:0;
font-family:Consolas;
font-size:32px;
font-weight:bold;
color:#5b21b6;
">
🎯 Generating The Synthetic Data
</h2>

</div>

In [3]:
import numpy as np #num- numerical    py-python
import pandas as pd # as- alias
np.random.seed(54)
n_student = 100

data = {
    "name" : np.random.choice(["Karan","Harsh","Nancy","Harshika"], n_student),
    "age" : np.random.randint(18, 25, n_student),
    "city" : np.random.choice(["Ambala","Radaur","Ladwa","Delhi"])
}
df = pd.DataFrame(data)
df

        name  age   city
0   Harshika   24  Ladwa
1      Harsh   22  Ladwa
2      Nancy   24  Ladwa
3   Harshika   24  Ladwa
4   Harshika   24  Ladwa
..       ...  ...    ...
95     Nancy   23  Ladwa
96     Karan   24  Ladwa
97     Harsh   19  Ladwa
98     Nancy   24  Ladwa
99     Karan   20  Ladwa

[100 rows x 3 columns]

In [4]:
import sqlite3 as sql
import pandas as pd

In [5]:
#connect a database [create if does not exist]
connection = sql.connect('base1.db')

In [6]:
# Create a cursor object using the connection
cursor = connection.cursor()
# cursor helps u to traverse over the records in a db

<div style="
background: linear-gradient(135deg, #f3e8ff, #ddd6fe);
padding:20px;
border-radius:15px;
text-align:center;
box-shadow:0 3px 8px rgba(0,0,0,0.1);
margin:auto;
">

<h2 style="
margin:0;
font-family:Consolas;
font-size:32px;
font-weight:bold;
color:#5b21b6;
">
🎯Fetching the Data
</h2>

</div>

In [7]:
cursor.execute('''CREATE TABLE feilds2(
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    age INTEGER,
    city TEXT           
);''')

In [8]:
connection.commit()

In [9]:
student_data= list(df.itertuples(index=False , name = None))
cursor.executemany("INSERT INTO feilds2(name, age, city) VALUES (?,?,?)", student_data)
connection.commit()

In [10]:
cursor.execute('''SELECT * FROM feilds2''')

In [11]:
results = cursor.fetchall()

<div style="
background: linear-gradient(135deg, #f3e8ff, #ddd6fe);
padding:20px;
border-radius:15px;
text-align:center;
box-shadow:0 3px 8px rgba(0,0,0,0.1);
margin:auto;
">

<h2 style="
margin:0;
font-family:Consolas;
font-size:32px;
font-weight:bold;
color:#5b21b6;
">
🎯 Printing Table
</h2>

</div>

In [ ]:
for record in results:
    print(record)

In [13]:
db = pd.DataFrame(results)
db

      0         1   2      3
0     1  Harshika  24  Ladwa
1     2     Harsh  22  Ladwa
2     3     Nancy  24  Ladwa
3     4  Harshika  24  Ladwa
4     5  Harshika  24  Ladwa
..  ...       ...  ..    ...
95   96     Nancy  23  Ladwa
96   97     Karan  24  Ladwa
97   98     Harsh  19  Ladwa
98   99     Nancy  24  Ladwa
99  100     Karan  20  Ladwa

[100 rows x 4 columns]

<div style="
background: linear-gradient(135deg, #f3e8ff, #ddd6fe);
padding:20px;
border-radius:15px;
text-align:center;
box-shadow:0 3px 8px rgba(0,0,0,0.1);
margin:auto;
">

<h2 style="
margin:0;
font-family:Consolas;
font-size:32px;
font-weight:bold;
color:#5b21b6;
">
🎯 Save CSV file
</h2>

</div>

In [17]:
df.to_csv("student_data", index = False)