<div style="background:linear-gradient(to right,#4A148C,#7B2CBF,#C77DFF);
padding:20px;
border-radius:18px;
text-align:center;">

<h1 style="color:white;
font-size:40px;
font-family:Georgia;
margin:0;">
📊 Placement Prediction System 📈
</h1>
</div>

<h2 style="
background:#7B2CBF;
color:white;
padding:10px 18px;
border-radius:8px;
display:inline-block;
font-family:'Segoe UI',sans-serif;">
📊 Generating the Synthetic data
</h2>

In [5]:
import numpy as np                        #num- numerical    py-python
import pandas as pd                       # as- alias
np.random.seed(15)
n_student = 1000

data = {   
    #student features
    "student_ID" : [f"User{i:03d}" for i in range(1, n_student + 1)],
    "Gender" : np.random.choice(["Male","Female"], n_student),
    "Age" : np.random.randint(20,22, n_student),
    "Department" : np.random.choice(["CSE","ECE","ME"], n_student),
    "Previous_academic_background" : np.random.choice(["A","B","C"], n_student),
    "Family_Income" : np.random.randint(10000,280000, n_student),

    #Academic features
    "Attendence_percentage" : np.clip(np.random.normal(75,15,n_student),20,100).round(1),
    "Semester_GPA " : np.clip(np.random.normal(7.0, 1.5, n_student),0, 10).round(2),                 
    "12th_percentage" :  np.clip(np.random.normal(75, 12, n_student), 0, 100),
    "Backlogs" : np.random.poisson(0.5,n_student),                                                 
    "certification_count" : np.random.randint(0,11, n_student),

    #skill feature
    "Aptitude_Test_Score" : np.clip(np.random.normal(75,15, n_student),0,100).round(2),               
    "Coding_Test_Score " : np.clip(np.random.normal(65,12, n_student),0,100).round(0),                               
    "Technical_Assessment_Score " : np.clip(np.random.normal(55,12, n_student),0,80).round(1),    
   
    #Experience Features
    "Internship_Count " : np.random.randint(0,6, n_student),
    "Project_Count " : np.random.randint(0,6, n_student),
    "Workshop_Participation " : np.random.randint(0,11, n_student),
    "Hackathon_Participation" : np.random.choice([0,1], n_student, p=[0.8,0.2]), 

    #Behavioural Features:
    "academic_warnings" : np.random.choice([0,1,2,3], n_student, p=[0.7, 0.2,0.08,0.02])
}
df = pd.DataFrame(data)
#print(data)
#print(df)
df

    student_ID  Gender  Age Department Previous_academic_background  \
0      User001    Male   20        ECE                            C
1      User002  Female   21        ECE                            B
2      User003    Male   20         ME                            B
3      User004  Female   20        CSE                            C
4      User005  Female   21        ECE                            B
5      User006    Male   20         ME                            C
6      User007    Male   21         ME                            B
7      User008  Female   21        ECE                            C
8      User009  Female   20         ME                            A
9      User010  Female   21        CSE                            B
10     User011  Female   21        CSE                            A
11     User012    Male   21         ME                            B
12     User013  Female   21        CSE                            A
13     User014  Female   21         ME                            C
14     User015  Female   20         ME                            B
15     User016  Female   20         ME                            A
16     User017  Female   20        CSE                            B
17     User018  Female   20        ECE                            C
18     User019    Male   20        CSE                            C
19     User020    Male   21         ME                            B
20     User021    Male   21        ECE                            C
21     User022  Female   20        ECE                            B
22     User023    Male   21        CSE                            A
23     User024  Female   21         ME                            A
24     User025  Female   20        CSE                            A
25     User026  Female   21         ME                            C
26     User027  Female   21        CSE                            B
27     User028    Male   20         ME                            C
28     User029  Female   20        CSE                            B
29     User030    Male   20        ECE                            B
30     User031  Female   20        ECE                            A
31     User032  Female   20         ME                            C
32     User033    Male   20         ME                            C
33     User034  Female   21        CSE                            C
34     User035    Male   21         ME                            C
35     User036    Male   21        CSE                            A
36     User037  Female   20         ME                            B
37     User038  Female   21        ECE                            A
38     User039  Female   21         ME                            C
39     User040    Male   21        ECE                            A
40     User041  Female   20         ME                            B
41     User042    Male   21        CSE                            B
42     User043    Male   21         ME                            A
43     User044  Female   21        CSE                            A
44     User045    Male   21        CSE                            A
45     User046  Female   20        CSE                            A
46     User047    Male   20         ME                            A
47     User048  Female   20        CSE                            A
48     User049    Male   21         ME                            B
49     User050  Female   21        ECE                            B
50     User051    Male   20        ECE                            C
51     User052    Male   20         ME                            C
52     User053    Male   20        CSE                            A
53     User054  Female   21         ME                            C
54     User055    Male   21        CSE                            C
55     User056  Female   21        ECE                            C
56     User057    Male   20        ECE                            A
57     User058    Male   20        ECE                            C
58     User059  Female   20        ECE                            C
59     User060    Male   20        CSE                            C
60     User061  Female   21         ME                            A
61     User062    Male   21        ECE                            B
62     User063    Male   20         ME                            A
63     User064    Male   20        CSE                            A
64     User065  Female   21        CSE                            C
65     User066  Female   20        CSE                            B
66     User067  Female   20         ME                            B
67     User068    Male   21        CSE                            A
68     User069  Female   20         ME                            B
69     User070    Male   20         ME                            B
70     User071  Female   21        CSE                            C
71     User072  Female   21        CSE                            B
72     User073  Female   21        CSE                            B
73     User074    Male   21         ME                            B
74     User075    Male   21        ECE                            B
75     User076  Female   20         ME                            C
76     User077  Female   20         ME                            B
77     User078  Female   21        ECE                            C
78     User079    Male   20         ME                            B
79     User080    Male   20         ME                            B
80     User081    Male   20        CSE                            B
81     User082    Male   20         ME                            B
82     User083    Male   21         ME                            B
83     User084  Female   20        CSE                            C
84     User085    Male   21        CSE                            A
85     User086    Male   21        CSE                            A
86     User087    Male   20        CSE                            C
87     User088  Female   20        CSE                            C
88     User089    Male   21        ECE                            A
89     User090  Female   21         ME                            B
90     User091  Female   21        CSE                            C
91     User092    Male   21         ME                            C
92     User093  Female   20         ME                            B
93     User094  Female   21        CSE                            A
94     User095  Female   21         ME                            C
95     User096    Male   21        CSE                            B
96     User097  Female   20         ME                            A
97     User098    Male   20        CSE                            C
98     User099    Male   20        ECE                            C
99     User100    Male   21         ME                            A
100    User101    Male   21         ME                            B
101    User102  Female   20        CSE                            B
102    User103    Male   20        CSE                            B
103    User104    Male   20         ME                            C
104    User105  Female   20         ME                            B
105    User106    Male   20        CSE                            C
106    User107    Male   20         ME                            B
107    User108    Male   21         ME                            C
108    User109    Male   20        CSE                            C
109    User110  Female   20        CSE                            C
110    User111  Female   21        ECE                            C
111    User112    Male   21        ECE                            C
112    User113  Female   20         ME                            B
113    User114    Male   21        ECE                            B
114    User115    Male   21         ME                            C
115    User116  Female   20         ME                            C
116    User117    Male   20        CSE                            B
117    User118    Male   20        CSE                            A
118    User119    Male   21        CSE                            B
119    User120    Male   20         ME                            A
120    User121    Male   20         ME                            A
121    User122  Female   21         ME                            B
122    User123    Male   20        CSE                            B
123    User124    Male   21        ECE                            B
124    User125  Female   21        CSE                            A
125    User126    Male   20        ECE                            B
126    User127    Male   20         ME                            B
127    User128    Male   20        CSE                            A
128    User129    Male   21        ECE                            B
129    User130    Male   21        ECE                            A
130    User131  Female   20         ME                            C
131    User132  Female   20        CSE                            C
132    User133  Female   20        ECE                            B
133    User134    Male   21        CSE                            C
134    User135  Female   21        ECE                            B
135    User136  Female   21         ME                            B
136    User137    Male   20         ME                            B
137    User138  Female   21        ECE                            A
138    User139  Female   21        CSE                            C
139    User140    Male   21        CSE                            B
140    User141  Female   20         ME                            A
141    User142  Female   21        CSE                            A
142    User143    Male   20         ME                            B
143    User144    Male   21        CSE                            A
144    User145  Female   20        CSE                            B
145    User146    Male   20        CSE                            B
146    User147    Male   21        ECE                            A
147    User148  Female   21        CSE                            B
148    User149    Male   20        ECE                            B
149    User150    Male   21         ME                            A
150    User151  Female   21        CSE                            B
151    User152    Male   20        ECE                            B
152    User153    Male   20         ME                            C
153    User154    Male   21        CSE                            A
154    User155  Female   21        ECE                            C
155    User156    Male   20        CSE                            C
156    User157    Male   20        CSE                            C
157    User158  Female   21        ECE                            B
158    User159  Female   20         ME                            C
159    User160  Female   20        ECE                            C
160    User161  Female   21        CSE                            B
161    User162    Male   20        ECE                            C
162    User163    Male   21         ME                            C
163    User164  Female   20        ECE                            A
164    User165  Female   20         ME                            B
165    User166    Male   21         ME                            A
166    User167  Female   20         ME                            A
167    User168  Female   21         ME                            C
168    User169    Male   20        CSE                            B
169    User170    Male   20         ME                            B
170    User171  Female   20        ECE                            B
171    User172  Female   21         ME                            A
172    User173    Male   20        CSE                            C
173    User174  Female   21         ME                            B
174    User175    Male   21        ECE                            B
175    User176  Female   21        ECE                            B
176    User177    Male   21         ME                            B
177    User178    Male   20        CSE                            C
178    User179    Male   21        CSE                            B
179    User180  Female   20        ECE                            C
180    User181  Female   20        CSE                            B
181    User182    Male   21        CSE                            A
182    User183    Male   20         ME                            C
183    User184  Female   20        ECE                            B
184    User185  Female   21        ECE                            B
185    User186    Male   20        CSE                            C
186    User187  Female   21         ME                            A
187    User188  Female   20         ME                            C
188    User189  Female   20        CSE                            A
189    User190  Female   20         ME                            B
190    User191    Male   20        ECE                            A
191    User192    Male   21         ME                            C
192    User193    Male   21         ME                            B
193    User194  Female   21        ECE                            A
194    User195  Female   21         ME                            C
195    User196  Female   21         ME                            C
196    User197    Male   20        CSE                            C
197    User198    Male   20        ECE                            A
198    User199  Female   21        ECE                            A
199    User200  Female   21        ECE                            C
200    User201  Female   21         ME                            A
201    User202    Male   20        CSE                            B
202    User203  Female   21        ECE                            C
203    User204    Male   20        ECE                            B
204    User205  Female   20        CSE                            B
205    User206  Female   20         ME                            C
206    User207  Female   20        CSE                            B
207    User208  Female   21        ECE                            B
208    User209  Female   21         ME                            B
209    User210  Female   21        ECE                            A
210    User211  Female   20        CSE                            C
211    User212  Female   21        CSE                            A
212    User213  Female   20        CSE                            B
213    User214  Female   20        ECE                            A
214    User215  Female   20        CSE                            C
215    User216    Male   20        CSE                            B
216    User217    Male   20         ME                            B
217    User218  Female   21        ECE                            A
218    User219    Male   21        ECE                            B
219    User220  Female   20        ECE                            A
220    User221  Female   20         ME                            A
221    User222    Male   20        CSE                            B
222    User223  Female   20         ME                            A
223    User224    Male   21        ECE                            B
224    User225  Female   21         ME                            A
225    User226    Male   20        ECE                            C
226    User227    Male   20        ECE                            B
227    User228  Female   21        ECE                            B
228    User229    Male   21         ME                            A
229    User230  Female   20        CSE                            B
230    User231    Male   21         ME                            A
231    User232  Female   20        CSE                            B
232    User233    Male   21        ECE                            B
233    User234  Female   21        CSE                            A
234    User235  Female   21         ME                            A
235    User236    Male   20         ME                            B
236    User237    Male   21        CSE                            C
237    User238    Male   20         ME                            C
238    User239    Male   21         ME                            A
239    User240    Male   20        CSE                            A
240    User241  Female   21         ME                            A
241    User242  Female   21         ME                            C
242    User243  Female   21        ECE                            B
243    User244    Male   20         ME                            A
244    User245  Female   20         ME                            C
245    User246    Male   20        ECE                            A
246    User247  Female   20        ECE                            B
247    User248    Male   21        ECE                            C
248    User249    Male   20        CSE                            A
249    User250    Male   20        ECE                            B
250    User251  Female   20         ME                            A
251    User252  Female   21         ME                            C
252    User253  Female   20         ME                            B
253    User254    Male   20        CSE                            B
254    User255  Female   20         ME                            A
255    User256    Male   21        CSE                            A
256    User257  Female   20        ECE                            B
257    User258    Male   20        CSE                            C
258    User259    Male   20        CSE                            A
259    User260    Male   20        ECE                            A
260    User261  Female   20        ECE                            A
261    User262  Female   20         ME                            C
262    User263    Male   20        CSE                            C
263    User264    Male   21        ECE                            C
264    User265    Male   21        CSE                            C
265    User266    Male   21         ME                            A
266    User267  Female   20        ECE                            A
267    User268  Female   20        ECE                            A
268    User269  Female   21        ECE                            C
269    User270    Male   20         ME                            C
270    User271    Male   20         ME                            C
271    User272  Female   21         ME                            B
272    User273    Male   20         ME                            A
273    User274    Male   20        CSE                            A
274    User275    Male   20        ECE                            A
275    User276  Female   20        ECE                            C
276    User277    Male   21        CSE                            B
277    User278    Male   21        ECE                            A
278    User279  Female   21         ME                            B
279    User280    Male   20        CSE                            C
280    User281    Male   21        CSE                            B
281    User282  Female   20        ECE                            B
282    User283  Female   20         ME                            C
283    User284  Female   21        ECE                            C
284    User285  Female   21        CSE                            B
285    User286  Female   21        CSE                            B
286    User287  Female   21         ME                            B
287    User288  Female   21        CSE                            B
288    User289    Male   20        ECE                            A
289    User290  Female   21        ECE                            B
290    User291    Male   21         ME                            C
291    User292    Male   21         ME                            B
292    User293    Male   20         ME                            C

<h2 style="
background:#7B2CBF;
color:white;
padding:10px 18px;
border-radius:8px;
display:inline-block;
font-family:'Segoe UI',sans-serif;">
📊 Calculating the risk score
</h2>

In [ ]:
risk_score = (
    0.30 * (df["Attendence_percentage"] < 60).astype(int) +
    0.15 * (df["Semester_GPA "] < 7.5).astype(int) +  # Trailing space included
    0.10 * (df["Aptitude_Test_Score"] > 70).astype(int) +
    0.10 * (df["academic_warnings"] > 0).astype(int) +
    0.10 * (df["Project_Count "] > 3).astype(int) +  # Added trailing space
    0.10 * (df["Backlogs"] >= 4).astype(int) +
    0.05 * (df["Technical_Assessment_Score "] > 55).astype(int) +  # Added trailing space
    0.05 * (df["Internship_Count "] > 3).astype(int) +  # Added trailing space
    0.10 * (df["Workshop_Participation "] > 5).astype(int) +  # Added trailing space
    0.05 * (df["Hackathon_Participation"] > 0).astype(int)
)

risk_score += np.random.normal(0, 0.05, len(df))

<h2 style="
background:#7B2CBF;
color:white;
padding:10px 18px;
border-radius:8px;
display:inline-block;
font-family:'Segoe UI',sans-serif;">
📊 Printing Table
</h2>

In [ ]:
df["Placement"] = (risk_score >= 0.50).astype(int)
df

    student_ID  Gender  Age Department Previous_academic_background  \
0      User001    Male   20        ECE                            C
1      User002  Female   21        ECE                            B
2      User003    Male   20         ME                            B
3      User004  Female   20        CSE                            C
4      User005  Female   21        ECE                            B
5      User006    Male   20         ME                            C
6      User007    Male   21         ME                            B
7      User008  Female   21        ECE                            C
8      User009  Female   20         ME                            A
9      User010  Female   21        CSE                            B
10     User011  Female   21        CSE                            A
11     User012    Male   21         ME                            B
12     User013  Female   21        CSE                            A
13     User014  Female   21         ME                            C
14     User015  Female   20         ME                            B
15     User016  Female   20         ME                            A
16     User017  Female   20        CSE                            B
17     User018  Female   20        ECE                            C
18     User019    Male   20        CSE                            C
19     User020    Male   21         ME                            B
20     User021    Male   21        ECE                            C
21     User022  Female   20        ECE                            B
22     User023    Male   21        CSE                            A
23     User024  Female   21         ME                            A
24     User025  Female   20        CSE                            A
25     User026  Female   21         ME                            C
26     User027  Female   21        CSE                            B
27     User028    Male   20         ME                            C
28     User029  Female   20        CSE                            B
29     User030    Male   20        ECE                            B
30     User031  Female   20        ECE                            A
31     User032  Female   20         ME                            C
32     User033    Male   20         ME                            C
33     User034  Female   21        CSE                            C
34     User035    Male   21         ME                            C
35     User036    Male   21        CSE                            A
36     User037  Female   20         ME                            B
37     User038  Female   21        ECE                            A
38     User039  Female   21         ME                            C
39     User040    Male   21        ECE                            A
40     User041  Female   20         ME                            B
41     User042    Male   21        CSE                            B
42     User043    Male   21         ME                            A
43     User044  Female   21        CSE                            A
44     User045    Male   21        CSE                            A
45     User046  Female   20        CSE                            A
46     User047    Male   20         ME                            A
47     User048  Female   20        CSE                            A
48     User049    Male   21         ME                            B
49     User050  Female   21        ECE                            B
50     User051    Male   20        ECE                            C
51     User052    Male   20         ME                            C
52     User053    Male   20        CSE                            A
53     User054  Female   21         ME                            C
54     User055    Male   21        CSE                            C
55     User056  Female   21        ECE                            C
56     User057    Male   20        ECE                            A
57     User058    Male   20        ECE                            C
58     User059  Female   20        ECE                            C
59     User060    Male   20        CSE                            C
60     User061  Female   21         ME                            A
61     User062    Male   21        ECE                            B
62     User063    Male   20         ME                            A
63     User064    Male   20        CSE                            A
64     User065  Female   21        CSE                            C
65     User066  Female   20        CSE                            B
66     User067  Female   20         ME                            B
67     User068    Male   21        CSE                            A
68     User069  Female   20         ME                            B
69     User070    Male   20         ME                            B
70     User071  Female   21        CSE                            C
71     User072  Female   21        CSE                            B
72     User073  Female   21        CSE                            B
73     User074    Male   21         ME                            B
74     User075    Male   21        ECE                            B
75     User076  Female   20         ME                            C
76     User077  Female   20         ME                            B
77     User078  Female   21        ECE                            C
78     User079    Male   20         ME                            B
79     User080    Male   20         ME                            B
80     User081    Male   20        CSE                            B
81     User082    Male   20         ME                            B
82     User083    Male   21         ME                            B
83     User084  Female   20        CSE                            C
84     User085    Male   21        CSE                            A
85     User086    Male   21        CSE                            A
86     User087    Male   20        CSE                            C
87     User088  Female   20        CSE                            C
88     User089    Male   21        ECE                            A
89     User090  Female   21         ME                            B
90     User091  Female   21        CSE                            C
91     User092    Male   21         ME                            C
92     User093  Female   20         ME                            B
93     User094  Female   21        CSE                            A
94     User095  Female   21         ME                            C
95     User096    Male   21        CSE                            B
96     User097  Female   20         ME                            A
97     User098    Male   20        CSE                            C
98     User099    Male   20        ECE                            C
99     User100    Male   21         ME                            A
100    User101    Male   21         ME                            B
101    User102  Female   20        CSE                            B
102    User103    Male   20        CSE                            B
103    User104    Male   20         ME                            C
104    User105  Female   20         ME                            B
105    User106    Male   20        CSE                            C
106    User107    Male   20         ME                            B
107    User108    Male   21         ME                            C
108    User109    Male   20        CSE                            C
109    User110  Female   20        CSE                            C
110    User111  Female   21        ECE                            C
111    User112    Male   21        ECE                            C
112    User113  Female   20         ME                            B
113    User114    Male   21        ECE                            B
114    User115    Male   21         ME                            C
115    User116  Female   20         ME                            C
116    User117    Male   20        CSE                            B
117    User118    Male   20        CSE                            A
118    User119    Male   21        CSE                            B
119    User120    Male   20         ME                            A
120    User121    Male   20         ME                            A
121    User122  Female   21         ME                            B
122    User123    Male   20        CSE                            B
123    User124    Male   21        ECE                            B
124    User125  Female   21        CSE                            A
125    User126    Male   20        ECE                            B
126    User127    Male   20         ME                            B
127    User128    Male   20        CSE                            A
128    User129    Male   21        ECE                            B
129    User130    Male   21        ECE                            A
130    User131  Female   20         ME                            C
131    User132  Female   20        CSE                            C
132    User133  Female   20        ECE                            B
133    User134    Male   21        CSE                            C
134    User135  Female   21        ECE                            B
135    User136  Female   21         ME                            B
136    User137    Male   20         ME                            B
137    User138  Female   21        ECE                            A
138    User139  Female   21        CSE                            C
139    User140    Male   21        CSE                            B
140    User141  Female   20         ME                            A
141    User142  Female   21        CSE                            A
142    User143    Male   20         ME                            B
143    User144    Male   21        CSE                            A
144    User145  Female   20        CSE                            B
145    User146    Male   20        CSE                            B
146    User147    Male   21        ECE                            A
147    User148  Female   21        CSE                            B
148    User149    Male   20        ECE                            B
149    User150    Male   21         ME                            A
150    User151  Female   21        CSE                            B
151    User152    Male   20        ECE                            B
152    User153    Male   20         ME                            C
153    User154    Male   21        CSE                            A
154    User155  Female   21        ECE                            C
155    User156    Male   20        CSE                            C
156    User157    Male   20        CSE                            C
157    User158  Female   21        ECE                            B
158    User159  Female   20         ME                            C
159    User160  Female   20        ECE                            C
160    User161  Female   21        CSE                            B
161    User162    Male   20        ECE                            C
162    User163    Male   21         ME                            C
163    User164  Female   20        ECE                            A
164    User165  Female   20         ME                            B
165    User166    Male   21         ME                            A
166    User167  Female   20         ME                            A
167    User168  Female   21         ME                            C
168    User169    Male   20        CSE                            B
169    User170    Male   20         ME                            B
170    User171  Female   20        ECE                            B
171    User172  Female   21         ME                            A
172    User173    Male   20        CSE                            C
173    User174  Female   21         ME                            B
174    User175    Male   21        ECE                            B
175    User176  Female   21        ECE                            B
176    User177    Male   21         ME                            B
177    User178    Male   20        CSE                            C
178    User179    Male   21        CSE                            B
179    User180  Female   20        ECE                            C
180    User181  Female   20        CSE                            B
181    User182    Male   21        CSE                            A
182    User183    Male   20         ME                            C
183    User184  Female   20        ECE                            B
184    User185  Female   21        ECE                            B
185    User186    Male   20        CSE                            C
186    User187  Female   21         ME                            A
187    User188  Female   20         ME                            C
188    User189  Female   20        CSE                            A
189    User190  Female   20         ME                            B
190    User191    Male   20        ECE                            A
191    User192    Male   21         ME                            C
192    User193    Male   21         ME                            B
193    User194  Female   21        ECE                            A
194    User195  Female   21         ME                            C
195    User196  Female   21         ME                            C
196    User197    Male   20        CSE                            C
197    User198    Male   20        ECE                            A
198    User199  Female   21        ECE                            A
199    User200  Female   21        ECE                            C
200    User201  Female   21         ME                            A
201    User202    Male   20        CSE                            B
202    User203  Female   21        ECE                            C
203    User204    Male   20        ECE                            B
204    User205  Female   20        CSE                            B
205    User206  Female   20         ME                            C
206    User207  Female   20        CSE                            B
207    User208  Female   21        ECE                            B
208    User209  Female   21         ME                            B
209    User210  Female   21        ECE                            A
210    User211  Female   20        CSE                            C
211    User212  Female   21        CSE                            A
212    User213  Female   20        CSE                            B
213    User214  Female   20        ECE                            A
214    User215  Female   20        CSE                            C
215    User216    Male   20        CSE                            B
216    User217    Male   20         ME                            B
217    User218  Female   21        ECE                            A
218    User219    Male   21        ECE                            B
219    User220  Female   20        ECE                            A
220    User221  Female   20         ME                            A
221    User222    Male   20        CSE                            B
222    User223  Female   20         ME                            A
223    User224    Male   21        ECE                            B
224    User225  Female   21         ME                            A
225    User226    Male   20        ECE                            C
226    User227    Male   20        ECE                            B
227    User228  Female   21        ECE                            B
228    User229    Male   21         ME                            A
229    User230  Female   20        CSE                            B
230    User231    Male   21         ME                            A
231    User232  Female   20        CSE                            B
232    User233    Male   21        ECE                            B
233    User234  Female   21        CSE                            A
234    User235  Female   21         ME                            A
235    User236    Male   20         ME                            B
236    User237    Male   21        CSE                            C
237    User238    Male   20         ME                            C
238    User239    Male   21         ME                            A
239    User240    Male   20        CSE                            A
240    User241  Female   21         ME                            A
241    User242  Female   21         ME                            C
242    User243  Female   21        ECE                            B
243    User244    Male   20         ME                            A
244    User245  Female   20         ME                            C
245    User246    Male   20        ECE                            A
246    User247  Female   20        ECE                            B
247    User248    Male   21        ECE                            C
248    User249    Male   20        CSE                            A
249    User250    Male   20        ECE                            B
250    User251  Female   20         ME                            A
251    User252  Female   21         ME                            C
252    User253  Female   20         ME                            B
253    User254    Male   20        CSE                            B
254    User255  Female   20         ME                            A
255    User256    Male   21        CSE                            A
256    User257  Female   20        ECE                            B
257    User258    Male   20        CSE                            C
258    User259    Male   20        CSE                            A
259    User260    Male   20        ECE                            A
260    User261  Female   20        ECE                            A
261    User262  Female   20         ME                            C
262    User263    Male   20        CSE                            C
263    User264    Male   21        ECE                            C
264    User265    Male   21        CSE                            C
265    User266    Male   21         ME                            A
266    User267  Female   20        ECE                            A
267    User268  Female   20        ECE                            A
268    User269  Female   21        ECE                            C
269    User270    Male   20         ME                            C
270    User271    Male   20         ME                            C
271    User272  Female   21         ME                            B
272    User273    Male   20         ME                            A
273    User274    Male   20        CSE                            A
274    User275    Male   20        ECE                            A
275    User276  Female   20        ECE                            C
276    User277    Male   21        CSE                            B
277    User278    Male   21        ECE                            A
278    User279  Female   21         ME                            B
279    User280    Male   20        CSE                            C
280    User281    Male   21        CSE                            B
281    User282  Female   20        ECE                            B
282    User283  Female   20         ME                            C
283    User284  Female   21        ECE                            C
284    User285  Female   21        CSE                            B
285    User286  Female   21        CSE                            B
286    User287  Female   21         ME                            B
287    User288  Female   21        CSE                            B
288    User289    Male   20        ECE                            A
289    User290  Female   21        ECE                            B
290    User291    Male   21         ME                            C
291    User292    Male   21         ME                            B
292    User293    Male   20         ME                            C

<h2 style="
background:#7B2CBF;
color:white;
padding:10px 18px;
border-radius:8px;
display:inline-block;
font-family:'Segoe UI',sans-serif;">
📊 Store in CSV file
</h2>

In [22]:
df.to_csv("student_placement_data", index = False)