<div style="
background: linear-gradient(135deg, #f3e8ff, #ddd6fe);
padding:20px;
border-radius:15px;
text-align:center;
box-shadow:0 3px 8px rgba(0,0,0,0.1);
margin:auto;
">

<h2 style="
margin:0;
font-family:Consolas;
font-size:32px;
font-weight:bold;
color:#5b21b6;
">
Gyansetu
</h2>

</div>

In [6]:
import requests
import pandas as pd
import json

In [7]:
url = "https://gyansetu.codroidhub.com/api/courses?view=user"

response = requests.get(url)

print("Status Code:", response.status_code)
print("Content-Type:", response.headers["Content-Type"])

Status Code: 200
Content-Type: application/json; charset=utf-8

In [8]:
data = response.json()

print(type(data))

<class 'dict'>

In [9]:
print(json.dumps(data, indent=4))

{
    "success": true,
    "count": 44,
    "data": [
        {
            "_id": "690890b99d0724561dcaa84d",
            "title": "Programming with C and C++",
            "subtitle": "Master fundamental programming concepts with C and object-oriented programming with C++",
            "slug": "programming-with-c-and-c++",
            "description": "Learn programming from the ground up with C and C++, the foundation of modern software development. \n  This comprehensive 30-day intensive course covers everything from basic syntax to advanced programming concepts. \n  You'll start with C programming fundamentals including algorithms, data types, operators, and control structures. \n  Progress to arrays, strings, functions, pointers, and file handling. Then transition to C++ to master object-oriented \n  programming concepts including classes, objects, inheritance, polymorphism, and virtual functions. Through daily \n  hands-on coding exercises, practical assignments, and real-world projects, you'll build a strong foundation in \n  programming logic, memory management, and modular programming. The course culminates in a final project: Student \n  Result Management System. Perfect for beginners starting their programming journey.",
            "shortDescription": "Intensive 30-day program covering C fundamentals, pointers, OOP with C++, and hands-on projects.",
            "image": "https://drive.codroidhub.com/skillyatra/courses/1762168218141-c-cpp.png",
            "thumbnail": "https://drive.codroidhub.com/skillyatra/courses/1762168218141-c-cpp.png",
            "duration": "6 weeks",
            "level": "Beginner",
            "category": {
                "_id": "693eed8a03de3e8b4db81676",
                "name": "Web Development",
                "id": "693eed8a03de3e8b4db81676"
            },
            "students": 0,
            "price": 10000,
            "isPublished": true,
            "language": [
                "English",
                "Hindi"
            ],
            "prerequisites": [
                "Basic computer operation skills",
                "No prior programming experience required",
                "Logical thinking and problem-solving aptitude",
                "Willingness to practice coding regularly"
            ],
            "whatYouWillLearn": [
                "Write and debug basic C programs and understand compilation process",
                "Master algorithms, flowcharts, and pseudocode for problem-solving",
                "Work with arrays, strings, and structures for data organization",
                "Understand pointers, memory management, and dynamic memory allocation",
                "Create modular programs using functions and recursion",
                "Perform file handling operations (read, write, append)",
                "Transition from procedural to object-oriented programming",
                "Implement OOP concepts: classes, objects, inheritance, polymorphism",
                "Build real-world projects like Calculator App and Student Result Management System",
                "Prepare for programming interviews and competitive coding"
            ],
            "requirements": [
                "Computer with Windows, Mac, or Linux operating system",
                "Minimum 4GB RAM (8GB recommended)",
                "Code editor or IDE (VS Code, Code::Blocks, or Visual Studio)",
                "C/C++ compiler (GCC or MinGW)",
                "Dedication to complete assignments and coding exercises"
            ],
            "modules": [
                {
                    "title": "Week 1 - Programming Fundamentals & C Basics",
                    "description": "Understand computer fundamentals, algorithms, and write basic C programs",
                    "lessons": [
                        {
                            "title": "Day 1: Introduction to Programming, Computer Components (CPU, Memory, OS, Compiler)",
                            "isFree": true,
                            "content": [],
                            "tools": [],
                            "pedagogy": [],
                            "outcomes": [],
                            "subTopics": [],
                            "_id": "690890b99d0724561dcaa84f"
                        },
                        {
                            "title": "Day 2: Algorithms, Flowcharts, Pseudocode",
                            "isFree": true,
                            "content": [],
                            "tools": [],
                            "pedagogy": [],
                            "outcomes": [],
                            "subTopics": [],
                            "_id": "690890b99d0724561dcaa850"
                        },
                        {
                            "title": "Day 3: C Syntax, Structure of a C Program, Data Types, Variables, Constants",
                            "isFree": false,
                            "content": [],
                            "tools": [],
                            "pedagogy": [],
                            "outcomes": [],
                            "subTopics": [],
                            "_id": "690890b99d0724561dcaa851"
                        },
                        {
                            "title": "Day 4: Operators (Arithmetic, Relational, Logical, Bitwise, Assignment)",
                            "isFree": false,
                            "content": [],
                            "tools": [],
                            "pedagogy": [],
                            "outcomes": [],
                            "subTopics": [],
                            "_id": "690890b99d0724561dcaa852"
                        },
                        {
                            "title": "Day 5: Conditional Statements (if, if-else, nested if, switch)",
                            "isFree": false,
                            "content": [],
                            "tools": [],
                            "pedagogy": [],
                            "outcomes": [],
                            "subTopics": [],
                            "_id": "690890b99d0724561dcaa853"
                        },
                        {
                            "title": "Day 6: Loops (for, while, do-while)",
                            "isFree": false,
                            "content": [],
                            "tools": [],
                            "pedagogy": [],
                            "outcomes": [],
                            "subTopics": [],
                            "_id": "690890b99d0724561dcaa854"
                        },
                        {
                            "title": "Day 7: Revision + Mini Task - Calculator App in C",
                            "isFree": false,
                            "content": [],
                            "tools": [],
                            "pedagogy": [],
                            "outcomes": [],
                            "subTopics": [],
                            "_id": "690890b99d0724561dcaa855"
                        }
                    ],
                    "order": 1,
                    "_id": "690890b99d0724561dcaa84e"
                },
                {
                    "title": "Week 2 - Arrays, Strings, Functions, and Pointers",
                    "description": "Learn structured data types and modular programming",
                    "lessons": [
                        {
                            "title": "Day 8: 1D Arrays and Basic Operations",
                            "isFree": false,
                            "content": [],
                            "tools": [],
                            "pedagogy": [],
                            "outcomes": [],
                            "subTopics": [],
                            "_id": "690890b99d0724561dcaa857"
                        },
                        {
                            "title": "Day 9: 2D Arrays, Matrix Addition & Multiplication",
                            "isFree": false,
                            "content": [],
                            "tools": [],
                            "pedagogy": [],
                            "outcomes": [],
                            "subTopics": [],
                            "_id": "690890b99d0724561dcaa858"
                        },
                        {
                            "title": "Day 10: Strings and Character Arrays",
                            "isFree": false,
                            "content": [],
                            "tools": [],
                            "pedagogy": [],
                            "outcomes": [],
                            "subTopics": [],
                            "_id": "690890b99d0724561dcaa859"
                        },
                        {
                            "title": "Day 11: Functions - Definition, Declaration, Call by Value",
                            "isFree": false,
                            "content": [],
                            "tools": [],
                            "pedagogy": [],
                            "outcomes": [],
                            "subTopics": [],
                            "_id": "690890b99d0724561dcaa85a"
                        },
                        {
                            "title": "Day 12: Recursion - Factorial, Fibonacci",
                            "isFree": false,
                            "content": [],
                            "tools": [],
                            "pedagogy": [],
                            "outcomes": [],
                            "subTopics": [],
                            "_id": "690890b99d0724561dcaa85b"
                        },
                        {
                            "title": "Day 13: Pointers - Basics and Applications",
                            "isFree": false,
                            "content": [],
                            "tools": [],
                            "pedagogy": [],
                            "outcomes": [],
                            "subTopics": [],
                            "_id": "690890b99d0724561dcaa85c"
                        },
                        {
                            "title": "Day 14: Structures - Defining, Array of Structures",
                            "isFree": false,
                            "content": [],
                            "tools": [],
                            "pedagogy": [],
                            "outcomes": [],
                            "subTopics": [],
                            "_id": "690890b99d0724561dcaa85d"
                        }
                    ],
                    "order": 2,
                    "_id": "690890b99d0724561dcaa856"
                },
                {
                    "title": "Week 3 - Advanced Concepts & File Handling (C \u2192 C++)",
                    "description": "Transition from structured to object-oriented thinking and explore storage/data management",
                    "lessons": [
                        {
                            "title": "Day 15: File Handling (Read, Write, Append Modes)",
                            "isFree": false,
                            "content": [],
                            "tools": [],
                            "pedagogy": [],
                            "outcomes": [],
                            "subTopics": [],
                            "_id": "690890b99d0724561dcaa85f"
                        },
                        {
                            "title": "Day 16: Storage Classes, Memory Layout",
                            "isFree": false,
                            "content": [],
                            "tools": [],
                            "pedagogy": [],
                            "outcomes": [],
                            "subTopics": [],
                            "_id": "690890b99d0724561dcaa860"
                        },
                        {
                            "title": "Day 17: Linked List Concepts",
                            "isFree": false,
                            "content": [],
                            "tools": [],
                            "pedagogy": [],
                            "outcomes": [],
                            "subTopics": [],
                            "_id": "690890b99d0724561dcaa861"
                        },
                        {
                            "title": "Day 18: Syntax & Semantics, Data Type Implementation",
                            "isFree": false,
                            "content": [],
                            "tools": [],
                            "pedagogy": [],
                            "outcomes": [],
                            "subTopics": [],
                            "_id": "690890b99d0724561dcaa862"
                        },
                        {
                            "title": "Day 19: Structured Data Objects, Dynamic Memory (malloc, free)",
                            "isFree": false,
                            "content": [],
                            "tools": [],
                            "pedagogy": [],
                            "outcomes": [],
                            "subTopics": [],
                            "_id": "690890b99d0724561dcaa863"
                        },
                        {
                            "title": "Day 20: Subprograms, Abstraction, Encapsulation Concepts",
                            "isFree": false,
                            "content": [],
                            "tools": [],
                            "pedagogy": [],
                            "outcomes": [],
                            "subTopics": [],
                            "_id": "690890b99d0724561dcaa864"
                        },
                        {
                            "title": "Day 21: Minor Test / Practical Assessment",
                            "isFree": false,
                            "content": [],
                            "tools": [],
                            "pedagogy": [],
                            "outcomes": [],
                            "subTopics": [],
                            "_id": "690890b99d0724561dcaa865"
                        }
                    ],
                    "order": 3,
                    "_id": "690890b99d0724561dcaa85e"
                },
                {
                    "title": "Week 4 - Introduction to C++ and OOP Concepts",
                    "description": "Learn principles of object-oriented programming using C++",
                    "lessons": [
                        {
                            "title": "Day 22: Introduction to C++ (History, Syntax Difference from C)",
                            "isFree": false,
                            "content": [],
                            "tools": [],
                            "pedagogy": [],
                            "outcomes": [],
                            "subTopics": [],
                            "_id": "690890b99d0724561dcaa867"
                        },
                        {
                            "title": "Day 23: Classes and Objects, Access Specifiers",
                            "isFree": false,
                            "content": [],
                            "tools": [],
                            "pedagogy": [],
                            "outcomes": [],
                            "subTopics": [],
                            "_id": "690890b99d0724561dcaa868"
                        },
                        {
                            "title": "Day 24: Constructors, Destructors",
                            "isFree": false,
                            "content": [],
                            "tools": [],
                            "pedagogy": [],
                            "outcomes": [],
                            "subTopics": [],
                            "_id": "690890b99d0724561dcaa869"
                        },
                        {
                            "title": "Day 25: Function Overloading, Operator Overloading",
                            "isFree": false,
                            "content": [],
                            "tools": [],
                            "pedagogy": [],
                            "outcomes": [],
                            "subTopics": [],
                            "_id": "690890b99d0724561dcaa86a"
                        },
                        {
                            "title": "Day 26: Inheritance - Types and Examples",
                            "isFree": false,
                            "content": [],
                            "tools": [],
                            "pedagogy": [],
                            "outcomes": [],
                            "subTopics": [],
                            "_id": "690890b99d0724561dcaa86b"
                        },
                        {
                            "title": "Day 27: Polymorphism, Virtual Functions, Abstract Classes",
                            "isFree": false,
                            "content": [],
                            "tools": [],
                            "pedagogy": [],
                            "outcomes": [],
                            "subTopics": [],
                            "_id": "690890b99d0724561dcaa86c"
                        },
                        {
                            "title": "Day 28: File Handling in C++",
                            "isFree": false,
                            "content": [],
                            "tools": [],
                            "pedagogy": [],
                            "outcomes": [],
                            "subTopics": [],
                            "_id": "690890b99d0724561dcaa86d"
                        },
                        {
                            "title": "Day 29: Storage Management (Stack, Heap, Static)",
                            "isFree": false,
                            "content": [],
                            "tools": [],
                            "pedagogy": [],
                            "outcomes": [],
                            "subTopics": [],
                            "_id": "690890b99d0724561dcaa86e"
                        },
                        {
                            "title": "Day 30: Final Assessment + Project - Student Result Management System",
                            "isFree": false,
                            "content": [],
                            "tools": [],
                            "pedagogy": [],
                            "outcomes": [],
                            "subTopics": [],
                            "_id": "690890b99d0724561dcaa86f"
                        }
                    ],
                    "order": 4,
                    "_id": "690890b99d0724561dcaa866"
                }
            ],
            "ratings": [],
            "createdAt": "2025-11-03T11:23:37.289Z",
            "updatedAt": "2026-06-22T07:31:38.987Z",
            "__v": 0,
            "jobOriginalPrice": 0,
            "jobPrice": 0,
            "summerOriginalPrice": 0,
            "summerPrice": 0,
            "isNepOnly": false,
            "isUniversityOnly": false,
            "showPrice": true,
            "brochure": null,
            "locations": [
                "69f1a9fb3a77079d946acf36",
                "6a0bff941f46ce7405c871d6"
            ],
            "mode": "Offline",
            "nepOriginalPrice": 0,
            "nepPrice": 0,
            "originalPrice": 10000,
            "paymentAccount": "1",
            "showDetailedSyllabus": false,
            "showSubTopics": false,
            "tools": [],
            "useDefaultPriceOnly": true,
            "workshopOriginalPrice": 0,

In [10]:
df = pd.DataFrame(data)

df.head()

   success  count                                               data
0     True     44  {'_id': '690890b99d0724561dcaa84d', 'title': '...
1     True     44  {'paymentAccount': '1', 'showDetailedSyllabus'...
2     True     44  {'_id': '69cb8ad00248fd6c27d27796', 'title': '...
3     True     44  {'paymentAccount': '1', 'showDetailedSyllabus'...
4     True     44  {'originalPrice': 0, 'useDefaultPriceOnly': Fa...

In [11]:
df = pd.DataFrame(data["data"])

df.head()

,_id,title,subtitle,slug,description,shortDescription,image,thumbnail,duration,level,...,showSubTopics,tools,useDefaultPriceOnly,workshopOriginalPrice,workshopPrice,id,registeredStudentsCount,registeredTeachersCount,traineeStudentsCount,universityStudentsCount
0,690890b99d0724561dcaa84d,Programming with C and C++,Master fundamental programming concepts with C...,programming-with-c-and-c++,Learn programming from the ground up with C an...,Intensive 30-day program covering C fundamenta...,https://drive.codroidhub.com/skillyatra/course...,https://drive.codroidhub.com/skillyatra/course...,6 weeks,Beginner,...,False,[],True,0,0,690890b99d0724561dcaa84d,0,0,0,0
1,69cb86c30248fd6c27d27689,DATA SCIENCE & ANALYTICS,"Master Data Handling, Visualization & Statisti...",data-analysis-with-python,"Build strong fundamentals in data analysis, st...",NaN,https://drive.codroidhub.com/gyansetu/Course/1...,https://drive.codroidhub.com/gyansetu/Course/1...,4 Weeks,Beginner,...,False,[],False,0,0,69cb86c30248fd6c27d27689,0,0,0,0
2,69cb8ad00248fd6c27d27796,Data Science and Analytics,"Master Data Analysis, Statistics & Predictive ...",advanced-data-analytics-machine-learning,"Build advanced skills in data analytics, stati...",NaN,https://drive.codroidhub.com/gyansetu/Course/1...,https://drive.codroidhub.com/gyansetu/Course/1...,6 Weeks,Intermediate,...,False,[],True,0,0,69cb8ad00248fd6c27d27796,3,0,3,0
3,69cb8b8a0248fd6c27d27a6a,DATA SCIENCE & ANALYTICS,"Master Data Science, Advanced Analytics & Real...",data-science-machine-learning,"Build strong expertise in data science, statis...",NaN,https://drive.codroidhub.com/skillyatra/course...,https://drive.codroidhub.com/gyansetu/Course/1...,12 Weeks,Advanced,...,False,[],False,0,0,69cb8b8a0248fd6c27d27a6a,0,0,0,0
4,69cb8cc70248fd6c27d27d38,DATA ENGINEERING & BIG DATA,Learn Data Engineering Fundamentals & Build Re...,data-engineering-big-data,"Master data engineering fundamentals, build ba...",NaN,https://drive.codroidhub.com/gyansetu/Course/1...,https://drive.codroidhub.com/gyansetu/Course/1...,4 Weeks,Beginner,...,False,[],False,0,0,69cb8cc70248fd6c27d27d38,0,0,0,0

In [12]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

df

,_id,title,subtitle,slug,description,shortDescription,image,thumbnail,duration,level,category,students,price,isPublished,language,prerequisites,whatYouWillLearn,requirements,modules,ratings,createdAt,updatedAt,__v,jobOriginalPrice,jobPrice,summerOriginalPrice,summerPrice,isNepOnly,isUniversityOnly,showPrice,brochure,locations,mode,nepOriginalPrice,nepPrice,originalPrice,paymentAccount,showDetailedSyllabus,showSubTopics,tools,useDefaultPriceOnly,workshopOriginalPrice,workshopPrice,id,registeredStudentsCount,registeredTeachersCount,traineeStudentsCount,universityStudentsCount
0,690890b99d0724561dcaa84d,Programming with C and C++,Master fundamental programming concepts with C...,programming-with-c-and-c++,Learn programming from the ground up with C an...,Intensive 30-day program covering C fundamenta...,https://drive.codroidhub.com/skillyatra/course...,https://drive.codroidhub.com/skillyatra/course...,6 weeks,Beginner,"{'_id': '693eed8a03de3e8b4db81676', 'name': 'W...",0,10000,True,"[English, Hindi]","[Basic computer operation skills, No prior pro...",[Write and debug basic C programs and understa...,"[Computer with Windows, Mac, or Linux operatin...",[{'title': 'Week 1 - Programming Fundamentals ...,[],2025-11-03T11:23:37.289Z,2026-06-22T07:31:38.987Z,0,0,0,0,0,False,False,True,None,"[69f1a9fb3a77079d946acf36, 6a0bff941f46ce7405c...",Offline,0,0,10000,1,False,False,[],True,0,0,690890b99d0724561dcaa84d,0,0,0,0
1,69cb86c30248fd6c27d27689,DATA SCIENCE & ANALYTICS,"Master Data Handling, Visualization & Statisti...",data-analysis-with-python,"Build strong fundamentals in data analysis, st...",NaN,https://drive.codroidhub.com/gyansetu/Course/1...,https://drive.codroidhub.com/gyansetu/Course/1...,4 Weeks,Beginner,"{'_id': '69a939214b5030b6a5d1eef4', 'name': 'N...",0,6500,True,[English],"[Basic understanding of computers, Interest in...",[Build strong Python foundation for data scien...,"[Laptop or computer with internet connection, ...",[{'title': 'Python Fundamentals for Data Scien...,[],2026-03-31T08:33:07.459Z,2026-04-09T15:40:31.970Z,0,0,0,0,0,False,False,False,None,[],Offline,6500,8000,0,1,False,False,[],False,0,0,69cb86c30248fd6c27d27689,0,0,0,0
2,69cb8ad00248fd6c27d27796,Data Science and Analytics,"Master Data Analysis, Statistics & Predictive ...",advanced-data-analytics-machine-learning,"Build advanced skills in data analytics, stati...",NaN,https://drive.codroidhub.com/gyansetu/Course/1...,https://drive.codroidhub.com/gyansetu/Course/1...,6 Weeks,Intermediate,"{'_id': '69a939214b5030b6a5d1eef7', 'name': 'S...",0,12000,True,[English],"[Basic knowledge of Python, Understanding of d...",[Translate business problems into data-driven ...,"[Laptop or computer with internet access, Pyth...",[{'title': 'Problem Framing & Data Understandi...,[],2026-03-31T08:50:24.743Z,2026-06-12T12:05:04.306Z,0,0,0,8500,12000,False,False,False,None,"[69f1a9fb3a77079d946acf36, 69f1a9f33a77079d946...",Offline,0,0,10000,2,False,False,[],True,0,0,69cb8ad00248fd6c27d27796,3,0,3,0
3,69cb8b8a0248fd6c27d27a6a,DATA SCIENCE & ANALYTICS,"Master Data Science, Advanced Analytics & Real...",data-science-machine-learning,"Build strong expertise in data science, statis...",NaN,https://drive.codroidhub.com/skillyatra/course...,https://drive.codroidhub.com/gyansetu/Course/1...,12 Weeks,Advanced,"{'_id': '69a939214b5030b6a5d1eefa', 'name': 'J...",0,40000,True,[English],"[Basic knowledge of Python, Understanding of d...",[Understand complete data science workflow and...,"[Laptop or computer with internet access, Pyth...","[{'title': 'Data Science Fundamentals', 'descr...",[],2026-03-31T08:53:30.197Z,2026-04-23T02:39:23.914Z,0,35000,40000,0,0,False,False,False,None,[],Offline,0,0,0,1,False,False,[],False,0,0,69cb8b8a0248fd6c27d27a6a,0,0,0,0
4,69cb8cc70248fd6c27d27d38,DATA ENGINEERING & BIG DATA,Learn Data Engineering Fundamentals & Build Re...,data-engineering-big-data,"Master data engineering fundamentals, build ba...",NaN,https://drive.codroidhub.com/gyansetu/Course/1...,https://drive.codroidhub.com/gyansetu/Course/1...,4 Weeks,Beginner,"{'_id': '69a939214b5030b6a5d1eef4', 'name': 'N...",0,6500,True,[English],"[Basic understanding of computers, Interest in...",[Understand the fundamentals of data engineeri...,"[Laptop or computer with internet access, Basi...","[{'title': 'Introduction to Data Engineering',...",[],2026-03-31T08:58:47.149Z,2026-04-05T15:45:31.218Z,0,0,0,0,0,False,False,False,None,[],Offline,6500,8000,0,1,False,False,[],False,0,0,69cb8cc70248fd6c27d27d38,0,0,0,0
5,69cb8d5b0248fd6c27d282e2,Data Engineering and Big Data,"Build Scalable Data Pipelines, Work with Big D...",data-engineering-pipeline-development,"Build real-world data pipelines, process data ...",NaN,https://drive.codroidhub.com/gyansetu/Course/1...,https://drive.codroidhub.com/gyansetu/Course/1...,6 Weeks,Intermediate,"{'_id': '69a939214b5030b6a5d1eef7', 'name': 'S...",0,8500,True,[English],[Basic knowledge of Python or any programming ...,[Translate business problems into scalable dat...,"[Laptop or computer with internet access, Deve...",[{'title': 'Problem Framing & Data Architectur...,[],2026-03-31T09:01:15.129Z,2026-05-11T05:56:49.723Z,0,0,0,8500,12000,False,False,False,None,"[69f1a9fb3a77079d946acf36, 69f2f93a21c7f18a72b...",Offline,0,0,0,2,False,False,[],False,0,0,69cb8d5b0248fd6c27d282e2,1,0,1,0
6,69cb8dc00248fd6c27d28721,DATA ENGINEERING & BIG DATA,"Master Scalable Data Pipelines, Big Data Proce...",advanced-data-engineering-big-data-systems,"Master advanced data engineering, big data sys...",NaN,https://drive.codroidhub.com/gyansetu/Course/1...,https://drive.codroidhub.com/gyansetu/Course/1...,12 Weeks,Advanced,"{'_id': '69a939214b5030b6a5d1eefa', 'name': 'J...",0,40000,True,[English],[Strong knowledge of Python or any programming...,[Design modern data engineering architectures ...,"[Laptop or computer with internet access, Deve...","[{'title': 'Data Engineering Architecture', 'd...",[],2026-03-31T09:02:56.689Z,2026-04-23T02:40:54.970Z,0,35000,40000,0,0,False,False,True,None,[],Offline,0,0,0,1,False,False,[],False,0,0,69cb8dc00248fd6c27d28721,0,0,0,0
7,69cb8f220248fd6c27d28e29,Artificial Intelligence and Machine Learning,"Learn AI Fundamentals, Data Analysis & Build M...",artificial-intelligence-and-machine-learning-4...,"Master AI fundamentals, perform data analysis,...",NaN,https://drive.codroidhub.com/gyansetu/Course/1...,https://drive.codroidhub.com/gyansetu/Course/1...,4 Weeks,Beginner,"{'_id': '69a939214b5030b6a5d1eef4', 'name': 'N...",0,6500,True,[English],"[Basic understanding of computers, Interest in...",[Understand Python fundamentals for AI and dat...,"[Laptop or computer with internet access, Pyth...","[{'title': 'Python Fundamentals for AI', 'desc...",[],2026-03-31T09:08:50.696Z,2026-04-05T15:53:29.012Z,0,0,0,0,0,False,False,False,None,[],Offline,6500,8000,0,1,False,False,[],False,0,0,69cb8f220248fd6c27d28e29,0,0,0,0
8,69cbab37d906079086c2356e,Artificial Intelligence & Machine Learning,"Master AI Product Thinking, Data Engineering, ...",ai-product-engineering-machine-learning-program,Learn how to transform business problems into ...,NaN,https://drive.codroidhub.com/skillyatra/course...,https://drive.codroidhub.com/skillyatra/course...,6 Weeks,Intermediate,"{'_id': '69a939214b5030b6a5d1eef7', 'name': 'S...",0,12000,True,[English],"[Basic understanding of programming concepts, ...",[Translate business problems into AI-driven so...,"[Laptop with internet connection, Python and b...",[{'title': 'Problem Framing & Product Thinking...,[],2026-03-31T11:08:39.476Z,2026-05-11T08:16:27.756Z,0,0,0,8500,12000,False,False,False,None,"[69f1a9fb3a77079d946acf36, 69f1a9ee3a77079d946...",Offline,0,0,10000,2,False,False,[],True,0,0,69cbab37d906079086c2356e,1,0,1,0
9,69cbaba2d906079086c24867,Artificial Intelligence & Machine Learning,"Design, Build, Scale, and Deploy Production-Re...",advanced-ai-engineering-mlops-program,Master advanced AI engineering concepts includ...,NaN,https://drive.codroidhub.com/gyansetu/Course/1...,https://drive.codroidhub.com/gyansetu/Course/1...,6 months,Advanced,"{'_id': '69a939214b5030b6a5d1eefa', 'name': 'J...",0,25000,True,[English],"[Basic understanding of machine learning, Fami...","[Design AI solutions from business problems, B...","[Laptop with stable internet connection, Pytho...",[{'title': 'Product Thinking & AI Solution Des...,[],2026-03-31T11:10:26.817Z,2026-06-22T09:52:24.999Z,0,35000,40000,0,0,False,False,False,None,[69f1a9fb3a77079d946acf36],Offline,0,0,0,1,False,False,[],False,0,0,69cbaba2d906079086c24867,0,0,0,0
10,69cd4b0ed906079086c305e7,Digital Marketing,"Master SEO, Paid Ads, Analytics & Real-World M...",advanced-digital-marketing,"Build real marketing campaigns, run ads, analy...",NaN,https://drive.codroidhub.com/skillyatra/course...,https://drive.codroidhub.com/skillyatra/course...,6 Weeks,Intermediate,"{'_id': '69a939214b5030b6a5d1eef7', 'name': 'S...",0,8000,True,[English],"[Basic understanding of digital marketing, Fam...",[Build complete marketing strategies and campa...,"[Laptop or computer with internet access, Goog...","[{'title': 'Marketing Strategy & Planning', 'd...",[],2026-04-01T16:42:54.289Z,2026-04-30T06:41:50.423Z,0,0,0,8500,12000,False,False,False,None,"[69f1a9fb3a77079d946acf36, 69f2f93a21c7f18a72b...",Offline,0,0,8000,1,False,False,[],True,0,0,69cd4b0ed906079086c305e7,1,0,1,0
11,69cd4b62d906079086c3182f,Digital Marketing,"Master Performance Marketing, Automation & Sca...",advanced-digital-marketing-growth,"Master advanced marketing strategies, scale ca...",NaN,https://drive.codroidhub.com/gyansetu/Course/1...,https://drive.codroidhub.com/gyansetu/Course/1...,12 Weeks,Advanced,"{'_id': '69a939214b5030b6a5d1eefa', 'name': 'J...",0,25000,True,[English],[Strong understanding of digital marketing fun...,[Build advanced marketing strategies and growt...,"[Laptop or computer with internet access, Goog...","[{'title': 'Advanced Marketing Strategy', 'des...",[],2026-04-01T16:44:18.928Z,2026-04-05T15:37:03.534Z,0,25000,35000,0,0,False,False,False,None,[],Offline,0,0,0,1,False,False,[],False,0,0,69cd4b62d906079086c3182f,0,0,0,0
12,69cd4d82d906079086c36570,UI/UX Design (Figma),"Master End-to-End Product Design, Advanced UI ...",advanced-ui-ux-design-product-design,"Master end-to-end product design, work on real...",NaN,https://drive.codroidhub.com/gyansetu/Course/1...,https://drive.codroidhub.com/gyansetu/Course/1...,12 Weeks,Advanced,"{'_id': '69a939214b5030b6a5d1eefa', 'name': 'J...",0,25000,True,[English],"[Strong understanding of UI/UX fundamentals, E...",[Conduct advanced UX research and user analysi...,"[Laptop or computer with internet access, Figm...","[{'title': 'Advanced UX Research', 'descriptio...",[],2026-04-01T16:53:22.340Z,2026-04-05T15:25:24.587Z,0,25000,35000,0,0,False,False,False,None,[],Offline,0,0,0,1,False,False,[],False,0,0,69cd4d82d906079086c36570,3,0,3,0
13,69cd4f5dd906079086c3aac9,React Native App Development,"Master Scalable Architecture, DevOps & Product...",advanced-mobile-app-engineering-scalable-systems,"Master advanced mobile development, build prod...",NaN,https://images.unsplash.com/photo-151632131842...,https://images.unsplash.com/photo-151632131842...,12 Weeks,Advanced,"{'_id': '69a939214b5030b6a5d1eefa', 'name': 'J...",0,25000,True,[English],"[Strong knowledge of React Native, Experience ...","[Design scalable mobile app architectures, Bui...","[Laptop with full development setup, Android/i...",[{'title': 'Advanced App Architecture & Scalab...,[],2026-04-01T17:01:17.238Z,2026-04-05T15:19:56.715Z,0,25000,35000,0,0,False,False,False,None,[],Offline,0,0,0,1,False,False,[],False,0,0,69cd4f5dd906079086c3aac9,0,0,0,0
14,69cd518bd906079086c3d076,Full Stack Engineering MERN,Learn Full Stack Web Development & Build Compl...,mern-stack-web-development,Master web development fundamentals with hands...,NaN,https://drive.codroidhub.com/gyansetu/Course/1...,https://drive.codroidhub.com/gyansetu/Course/1...,4 Weeks,Beginner,"{'_id': '69a939214b5030b6a5d1eef4', 'name': 'N...",0,6500,True,[English],"[Basic understanding of computers, Interest in...","[Build responsive web interfaces using HTML, C...","[Laptop or computer with internet access, Code...","[{'title': 'Web Development Fundamentals', 'de...",[],2026-04-01T17:10:35.661Z,2026-04-05T14:21:21.086Z,0,0,0,0,0,False,False,False,None,[],Offline,6500,8000,0,1,False,False,[],False,0,0,69cd518bd906079086c3d076,0,0,0,0
15,69cd51ddd906079086c3edce,Full Stack Engineering MERN,"Build Scalable Applications, Integrate APIs & ...",advanced-mern-stack-development,"Master advanced MERN and AI skills, build real...",NaN,https://drive.codroidhub.com/gyansetu/Course/1...,https://drive.codroidhub.com/gyansetu/Course/1...,6 Weeks,Intermediate,"{'_id': '69a939214b5030b6a5d1eef7', 'name': 'S...",0,10000,True,[English],"[Basic knowledge of HTML, CSS, JavaScript, Und...","[Build scalable full-stack applications, Use a...","[Laptop with development setup, Node.js and Mo...","[{'title': 'Web Development Fundamentals', 'de...",[],2026-04-01T17:11:57.860Z,2026-06-12T12:04:09.662Z,0,0,0,8500,12000,False,False,False,None,"[69f1a9fb3a77079d946acf36, 69f1a9ee3a77079d946...",Offline,0,0,8000,1,False,False,[],True,0,0,69cd51ddd906079086c3edce,10,0,10,0
16,69cd5213d906079086c40bec,Full Stack Engineering MERN,"Master Scalable Systems, DevOps & Become Job-R...",full-stack-engineering-production-systems-mern,"Master advanced full stack development, build ...",NaN,https://drive.codroidhub.com/gyansetu/Course/1...,https://drive.codroidhub.com/gyansetu/Course/1...,12 Weeks,Advanced,"{'_id': '69a939214b5030b6a5d1eefa', 'name': 'J...",0,35000,True,[English],"[Strong knowledge of MERN stack, Experience wi...",[Design scalable web application architectures...,"[Laptop with full development setup, Node.js, ...","[{'title': 'Advanced Web Foundations', 'descri...",[],2026-04-01T17:12:51.311Z,2026-04-05T14:19:42.497Z,0,25000,35000,0,0,False,False,False,None,[],Offline,0,0,0,1,False,False,[],False,0,0,69cd5213d906079086c40bec,0,0,0,0
17,69cdf79cd906079086c4c55f,Cloud Computing with AWS,"Design Scalable Cloud Systems, Automate Deploy...",advanced-cloud-architecture-devops-engineering...,"Master advanced cloud architecture, DevOps aut...",NaN,https://drive.codroidhub.com/gyansetu/Course/1...,https://drive.codroidhub.com/gyansetu/Course/1...,12 Weeks,Advanced,"{'_id': '69a939214b5030b6a5d1eefa', 'name': 'J...",0,25000,True,[English],"[Basic knowledge of cloud computing, Familiari...",[Design scalable and distributed cloud archite...,"[Laptop with internet connection, AWS account ...","[{'title': 'Advanced Cloud Architecture', 'des...",[],2026-04-02T04:59:08.638Z,2026-04-05T13:51:21.965Z,0,25000,35000,0,0,False,False,False,None,[],Offline,0,0,0,1,False,False,[],False,0,0,69cdf79cd906079086c4c55f,0,0,0,0
18,69cdf95fd906079086c500ac,Graphic Design,"Learn Design Principles, Tools, and Create Rea...",graphic-design-fundamentals-program,"Learn the fundamentals of graphic design, incl...",NaN,https://drive.codroidhub.com/gyansetu/Course/1...,https://drive.codroidhub.com/gyansetu/Course/1...,4 Weeks,Beginner,"{'_id': '69a939214b5030b6a5d1eef4', 'name': 'N...",0,650,True,[English],"[Basic computer knowledge, Interest in graphic...",[Understand core graphic design principles and...,"[Laptop or desktop with internet connection, D...","[{'title': 'Introduction to Graphic Design', '...",[],2026-04-02T05:06:39.381Z,2026-04-05T13:50:45.824Z,0,0,0,0,0,False,False,False,None,[],Offline,6500,8000,0,1,False,False,[],False,0,0,69cdf95fd906079086c500ac,0,0,0,0
19,69cdfda4d906079086c542b8,Graphic Design,"Master Branding, Advanced Design Techniques, a...",advanced-graphic-design-creative-strategy-program,Learn advanced graphic design concepts includi...,NaN,https://drive.codroidhub.com/gyansetu/Course/1...,https://drive.codroidhub.com/gyansetu/Course/1...,6 Weeks,Advanced,"{'_id': '69a939214b5030b6a5d1eef7', 'name': 'S...",0,12000,True,[English],[Basic knowledge of graphic design fundamental...,[Plan and execute professional design projects...,"[Laptop or desktop with internet connection, D...","[{'title': 'Design Workflow & Strategy', 'desc...",[],2026-04-02T05:24:52.938Z,2026-04-30T06:43:34.110Z,0,0,0,8500,12000,False,False,False,None,"[69f1a9fb3a77079d946acf36, 69f2f93a21c7f18a72b...",Offline,0,0,0,1,False,False,[],False,0,0,69cdfda4d906079086c542b8,0,0,0,0
20,69cdff80d906079086c56d18,Graphic Design,"Master Design Systems, AI-Powered Creativity, ...",advanced-creative-design-ai-visual-systems-pro...,"Learn advanced design systems, branding, creat...",NaN,https://drive.codroidhub.com/gyansetu/Course/1...,https://drive.codroidhub.com/gyansetu/Course/1...,12 Weeks,Advanced,"{'_id': '69a939214b5030b6a5d1eefa', 'name': 'J...",0,25000,True,[English],"[Basic knowledge of graphic design, Familiarit...","[Build scalable and consistent design systems,...","[Laptop or desktop with internet connection, D...","[{'title': 'Advanced Design Systems', 'descrip...",[],2026-04-02T05:32:48.188Z,2026-04-05T13:45:26.440Z,0,25000,35000,0,0,False,False,False,None,[],Offline,0,0,0,1,False,False,[],False,0,0,69cdff80d906079086c56d18,0,0,0,0
21,69ce0724d906079086c5c822,Smart Systems & IoT Engineering,Design Intelligent IoT Systems with AI Integra...,advanced-aiot-smart-systems-engineering-program,"Learn advanced concepts of smart systems, IoT ...",NaN,https://drive.codroidhub.com/gyansetu/Course/1...,https://drive.codroidhub.com/gyansetu/Course/1...,6 Weeks,Advanced,"{'_id': '69a939214b5030b6a5d1eef7', 'name': 'S...",0,8500,True,[English],"[Basic knowledge of IoT and embedded systems, ...","[Design scalable smart system architectures, W...","[Laptop with internet connection, IoT hardware...","[{'title': 'Smart System Architecture', 'descr...",[],2026-04-02T06:05:24.987Z,2026-04-30T06:44:00.774Z,0,0,0,8500,12000,False,False,False,None,"[69f1a9fb3a77079d946acf36, 69f2f93a21c7f18a72b...",Offline,0,0,0,1,False,False,[],False,0,0,69ce0724d906079086c5c822,0,0,0,0
22,69ce0857d906079086c5e306,Smart Systems & IoT Engineering,"Build Intelligent, Scalable, and Secure Smart ...",advanced-aiot-systems-scalable-smart-engineeri...,Master advanced AIoT systems including scalabl...,NaN,https://drive.codroidhub.com/gyansetu/Course/1...,https://drive.codroidhub.com/gyansetu/Course/1...,12 Weeks,Advanced,"{'_id': '69a939214b5030b6a5d1eefa', 'name': 'J...",0,25000,True,[English],"[Strong understanding of IoT fundamentals, Bas...",[Design large-scale and distributed smart syst...,"[Laptop with internet connection, IoT hardware...",[{'title': 'Advanced Smart System Architecture...,[],2026-04-02T06:10:31.225Z,2026-04-05T13:43:12.451Z,0,25000,35000,0,0,False,False,False,None,[],Offline,0,0,0,1,False,False,[],False,0,0,69ce0857d906079086c5e306,0,0,0,0
23,69ce0b9ed906079086c60187,Generative AI & LLM Engineering,"Learn AI Fundamentals, Prompt Engineering, and...",generative-ai-prompt-engineering-program,"Explore the world of Generative AI, understand...",NaN,https://drive.codroidhub.com/gyansetu/Course/1...,https://drive.codroidhub.com/gyansetu/Course/1...,4 Weeks,Beginner,"{'_id': '69a939214b5030b6a5d1eef4', 'name': 'N...",0,6500,True,[English],"[Basic computer knowledge, Interest in AI and ...",[Understand core concepts of Generative AI and...,"[Laptop with internet connection, Access to AI...","[{'title': 'Introduction to Generative AI', 'd...",[],2026-04-02T06:24:30.484Z,2026-04-05T15:50:52.584Z,0,0,0,0,0,False,False,False,None,[],Offline,7000,8000,0,1,False,False,[],False,0,0,69ce0b9ed906079086c60187,0,0,0,0

In [13]:
df.to_csv("GyanSetu_Courses.csv", index=False)

print("CSV Saved Successfully!")

CSV Saved Successfully!